#include<stdio.h>

int main(){
  printf("In the fullness of time \e[0;31mMS-DOS\e[0m begat \e[0;31mWindows\e[0m. And this is the lineage of \e[0;31mWindows\e[0m: \e[0;31mCP/M\e[0m begat \e[0;31mQDOS\e[0m. \e[0;31mQDOS\e[0m begat \e[0;31mDOS 1.0\e[0m. \e[0;31mDOS 1.0\e[0m begat \e[0;31mDOS 2.0\e[0m by way of \e[0;31mUnix\e[0m. \e[0;31mDOS 2.0\e[0m begat \e[0;31mWindows 3.11\e[0m by way of \e[0;34mPARC\e[0m and Macintosh. \e[0;34m IBM\e[0m and\e[0;34m Microsoft\e[0m begat \e[0;31mOS/2\e[0m, who begat \e[0;31mWindows NT\e[0m and \e[0;31mWarp\e[0m, the lost OS of lore.\e[0;31mWindows 3.11\e[0m begat \e[0;31mWindows 95\e[0m after triumphing over Macintosh in a mighty Battle of Licences. \e[0;31mWindows NT\e[0m begat \e[0;31mNT 4.0\e[0m by way of \e[0;31mWindows 95\e[0m. \e[0;31mNT 4.0\e[0m begat \e[0;31mNT 5.0\e[0m, the OS also called \e[0;31mWindows 2000\e[0m, The Millenium Bug, Doomsday , Armageddon , The End Of All Things.\n");
  printf("\nNow it came to pass that\e[0;34m Microsoft\e[0m had waxed great and mighty among the Microchip Corporations mighter than any of the Mainframe Corporations before it had it waxed. And\e[0;34m Gates\e[0m heart was hardened , and he swore unto his Customers and their Engineers the words of this curse:\n");
  printf("\n\"Children of\e[0;34m von Neumann\e[0m , hear me. \e[0;34m IBM\e[0m and the\e[0;34m Mainframe Corporations\e[0m bound thy forefathers with grave and perilous Licences , such that ye cried unto the spirits of\e[0;34m Turing\e[0m and\e[0;34m von Neumann\e[0m for deliverance. Now I say unto ye: I am greater than any Corporation before me. Will I loosen your Licences ? Nay, I will bind thee with Licences twice as grave and ten times more perilous than my forefathers. I will engrave my Licence on thy heart and write my Serial Number upon thy frontal lobes. I will bind thee to the \e[0;31mWindows\e[0m Platform with cunning artifices and with devious schemes. I will bind thee to the\e[0;34m Intel\e[0m Chipset with crufty code and with gnarly APIs. I will capture and enslave thee as no generation has been enslaved before. And wherefore will ye cry then unto the spirits of\e[0;34m Turing\e[0m , and\e[0;34m von Neumann\e[0m , and\e[0;34m Moore\e[0m? They cannot hear ye. I am become a greater Power than they. Ye shall cry only unto me, and shall live by my mercy and my wrath. I am the Gates of Hell; I hold the portal to\e[0;34m MSNBC\e[0m and the keys to the Blue Screen of Death. Be ye afraid; be ye greatly afraid; serve only me, and live.\"\n");
  printf("\nAnd the people were cowed in terror and gave homage to\e[0;34m Microsoft\e[0m , and endured the many grave and perilous trials which the \e[0;31mWindows\e[0m platform and its greatly bogacious Licence forced upon them. And once again did they cry to\e[0;34m Turing\e[0m and\e[0;34m von Neumann\e[0m and\e[0;34m Moore\e[0m for a deliverer , but none was found equal to the task until the birth of \e[0;31mLinux\e[0m.\n");
  printf("\nThese are the generations of \e[0;31mLinux\e[0m:\n");
  printf("\n\e[0;34mSAGE\e[0m begat\e[0;34m ARPA\e[0m, which begat TCP/IP, and Aloha , which begat Ethernet. \e[0;34m Bell\e[0m begat \e[0;31mMultics\e[0m , which begat C, which begat \e[0;31mUnix\e[0m. \e[0;31mUnix\e[0m and TCP/IP begat Internet , which begat the World Wide Web. \e[0;31mUnix\e[0m begat \e[0;31mRMS\e[0m, father of the great \e[0;31mGNU\e[0m, which begat the Libraries and Emacs , chief of the Utilities. In the days of the Web, Internet and Ethernet begat the Intranet LAN, which rose to renown among all Corporations and prepared the way for the Penguin. And\e[0;34m Linus\e[0m and the Web begat the Kernel through \e[0;31mUnix\e[0m. The Kernel , the Libraries and the Utilities together are the Distribution , the one Penguin in many forms , forever and ever praised.\n");
  return 0;
}